#!/bin/bash

#assume once snakemake-ified will have access to  config options:
# 1) the species code
# 2) the path to use for coverage files

# once snakemake-ified should run a separate job for each bam file, so currently writing to take a specific file
# this will presumably be auto-generated by snakemake eventually

set -o errexit

SPECIES=$1
COVPATH=$2

ls ${COVPATH}/*.bw > ${COVPATH}/${SPECIES}_bigWig_list
bigWigMerge -inList ${COVPATH}/${SPECIES}_bigWig_list ${COVPATH}/${SPECIES}.merge.bg
bedGraphToBigWig ${COVPATH}/${SPECIES}.merge.bg ${COVPATH}/${SPECIES}.chrom.sizes ${COVPATH}/${SPECIES}.merge.bw
bigWigAverageOverBed ${COVPATH}/${SPECIES}.merge.bw ${COVPATH}/${SPECIES}.genome.bed ${COVPATH}/${SPECIES}.summary.tab
gzip ${COVPATH}/${SPECIES}.merge.bg
